### ISSUE TITLE
It writes temporary AppData

### ISSUE THREAD

**Issue by angelog0** [portapps/vlc-portable#5]
I noticed that when one start VLC an `AppData\Roaming\vlc` folder is created and this folder is removed closing the app. I wonder if this is a bug or feature for an app that aims to be portable..

**Comment by crazy-max** [comment]
@angelog0 It's a feature. Some paths are hardcoded inside VLC like `dvdcss`, `ml.xspf`, `vlc-qt-interface.ini`, etc..
